input:
  delete: no
  dir: "/tmp/dmarc_files/"
  #imap:
  #  server: ""
  #  username: ""
  #  password: ""
  #  mailbox: ""
  # enable debug messages for imap package?
  #  debug: no
  # delete emails from server after fetch?
  #  delete: no

output:
  # output file
  # should be: string, golang template string or "stdout"
  file: "/tmp/html/{{ .ID }}.html"
  # file: "/tmp/html/{{ .ReportMetadata.Email }}/{{ .PolicyPublished.Domain }}!{{.ReportMetadata.DateRange.Begin}}!{{ .ReportMetadata.ReportID }}.html"

  # output format
  # should be: txt, json, html_static, html
  format: "html_static"

  # if you configure format to "html" output, don't forget to configure assets_path and your web server
  # assets_path: "./assets"

# perform reverse lookups?
lookup_addr: no

# merge multiple similar reports to one?
merge_reports: yes

log_debug: no
log_datetime: no
